# Generated by Django 5.1.2 on 2024-10-18 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_user_email_expenses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expenses',
            new_name='ExpenseModel',
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='UserModel',
        ),
    ]
